# Generated by Django 4.2.9 on 2024-11-11 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Registrationform',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=255)),
                ('phone_number', models.CharField(max_length=20)),
                ('email', models.EmailField(max_length=254)),
                ('position', models.CharField(choices=[('select', 'Select your position'), ('LCP', 'LCP'), ('LCVP', 'LCVP'), ('MM', 'MM'), ('TM', 'TM')], default='select', max_length=100)),
                ('function', models.CharField(choices=[('select', 'Select your function'), ('OGV', 'OGV'), ('OGT', 'OGT'), ('IGV', 'IGV'), ('IGTa', 'IGTa'), ('B2C', 'B2C'), ('B2B', 'B2B'), ('MXP', 'MXP'), ('F and L', 'F and L')], default='select', max_length=100)),
                ('id_front', models.FileField(upload_to='idfront/%y/%m/%d')),
                ('id_back', models.FileField(upload_to='idback/%y/%m/%d')),
                ('indemnity_form', models.FileField(upload_to='indemnityform/%y/%m/%d')),
                ('personal_photo', models.ImageField(upload_to='personalphoto/%y/%m/%d')),
                ('submitted_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
